version: '3'
services:
  chrome83:
    image: selenoid/vnc:chrome_83.0
    container_name: chrome
    privileged: true
    shm_size: '1g'
    tty: true
    command: ["-limit", "1", "-mem", "1g", "-cpu", "1g", "-session-delete-timeout", "3m", "-timeout", "2m"]
    ports:
      - "4444:4444"
      
  # chrome68:
  #   image: selenoid/chrome:68.0
  videorecorder:
    image: selenoid/video-recorder
    logging:
      driver: none
