version: "2"
services:
  esgiuitest-container:
    container_name: esgiuitest-container
    build: .
    ports:
      - "3000:8080"  
    networks:
      testing_net:
          ipv4_address: 172.28.1.2
    depends_on:
      - selenoid
    volumes:
      - ./tests:/tests
      - ./package.json:/package.json
      - ./package-lock.json:/package-lock.json
      - ./.gitignore:/.gitignore
      - ${PWD}/reports/allure-results:/usr/src/app/reports/allure-results
      - ${PWD}/screenshots:/usr/src/app/screenshots
      - ${PWD}/errorshots:/usr/src/app/errorshots
   
  selenoid:
    container_name: selenoid
    image: selenoid/chrome:81.0
    volumes:
      - /dev/shm:/dev/shm
    ports:
      - "4444:4444"
    networks:
          testing_net:
              ipv4_address: 172.28.1.1

  allure:
    container_name: allure
    image: "frankescobar/allure-docker-service"
    environment:
      CHECK_RESULTS_EVERY_SECONDS: 1
      KEEP_HISTORY: "TRUE"
    ports:
      - "4040:4040"
      - "5050:5050"
    volumes:
       - ${PWD}/reports/allure-results:/app/allure-results

networks:
    testing_net:
        ipam:
            driver: default
            config:
                - subnet: 172.28.0.0/16