version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - echo Installing Test dependencies
      - npm install --silent
      - echo Finished installing Test dependencies
  build:
    commands:
      - echo Running UI Tests
      - npm run reports
      - echo Building artifacts
      - npm run build
      - echo Deploying artifacts
      - npm run deploy-dev
      - echo Invalidating cloudfront cache
      - npm run cache-bust-dev

cache:
  paths:
    - "node_modules/**/*"

artifacts:
  files:
    - "**/*"
  base-directory: "frontend/build*"
  discard-paths: no



  version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - echo Installing Test dependencies
      - npm install --silent
      - echo Finished installing Test dependencies
  build:
    commands:
      - echo Running UI Tests
      - npm run reports
      - npm run allure-report
      - echo Deploying artifacts
      - npm run deploy-results
cache:
  paths:
    - "node_modules/**/*"

artifacts:
  files:
    - "**/*"
  base-directory: "allure-report/*"
  discard-paths: no